version: '3'

services:
  jupyterlab:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "{{ cookiecutter.python_package_name }}"
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    ports:
      - '8888:8888'
    volumes:
      - $PWD:/home